# Generated by Django 2.2.7 on 2020-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.TextField(max_length=99999),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(max_length=999),
        ),
    ]
