# Generated by Django 2.2.7 on 2020-03-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200316_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Gst',
            field=models.CharField(blank=True, default=50, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Tel',
            field=models.IntegerField(blank=True, default=50, max_length=10, null=True),
        ),
    ]
