# Generated by Django 2.2.7 on 2020-03-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Initial_Balance',
            field=models.DecimalField(decimal_places=2, max_digits=999999),
        ),
    ]
