# Generated by Django 2.2.7 on 2020-03-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20200316_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Initial_Balance',
        ),
    ]
