# Generated by Django 2.2.7 on 2020-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_client_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbalance',
            name='Initial_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999, null=True),
        ),
    ]
