# Generated by Django 2.2.7 on 2020-03-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_clientbalance_initial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Gst_no',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
