# Generated by Django 2.2.7 on 2020-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='')),
                ('Title', models.CharField(max_length=1200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9999999)),
            ],
        ),
    ]
