# Generated by Django 2.2.7 on 2020-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_prod_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_quantity',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
