# Generated by Django 2.2.7 on 2020-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200317_0006'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.AddField(
            model_name='orders',
            name='client',
            field=models.ManyToManyField(to='product.Prod_quantity'),
        ),
    ]
