# Generated by Django 2.2.7 on 2020-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200317_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('inital', 'inital'), ('process', 'process'), ('deliver', 'deliver'), ('cancel', 'cancel')], default='inital', max_length=122251985),
        ),
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Prod_quantity'),
        ),
    ]
