# Generated by Django 2.2.7 on 2020-03-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200317_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Initial_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='Total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='balance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999, null=True),
        ),
    ]
